//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Pokemon_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerPokemon
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Height { get; set; }
        public decimal Weight { get; set; }
        public int Xp { get; set; }
        public int PokemonId { get; set; }
        public int PlayerId { get; set; }
        public bool InParty { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Pokemon Pokemon { get; set; }
    }
}
