//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Pokemon_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Project_Pokemon_Entities : DbContext
    {
        public Project_Pokemon_Entities()
            : base("name=Project_Pokemon_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Attack> Attacks { get; set; }
        public virtual DbSet<Found> Founds { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Npc> Npcs { get; set; }
        public virtual DbSet<NpcItem> NpcItems { get; set; }
        public virtual DbSet<OwnedPokemonAttack> OwnedPokemonAttacks { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<PlayerItem> PlayerItems { get; set; }
        public virtual DbSet<PlayerPokedex> PlayerPokedexes { get; set; }
        public virtual DbSet<PlayerPokemon> PlayerPokemons { get; set; }
        public virtual DbSet<Pokedex> Pokedexes { get; set; }
        public virtual DbSet<Pokemon> Pokemons { get; set; }
        public virtual DbSet<PokemonAttack> PokemonAttacks { get; set; }
        public virtual DbSet<TrainerPokemon> TrainerPokemons { get; set; }
        public virtual DbSet<Type> Types { get; set; }
    }
}
