//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Pokemon_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerPokemon
    {
        public int Id { get; set; }
        public int PokemonId { get; set; }
        public int NpcId { get; set; }
    
        public virtual Npc Npc { get; set; }
        public virtual Pokemon Pokemon { get; set; }
    }
}
